//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poc.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Newtonsoft.Json;
    
    
    [MetadataType(typeof(CategoryMetadata))]
    public partial class Category
    {
        public Category()
        {
    		/*
    			Product,
    		*/
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string SessionId { get; set; }
        public System.DateTime CreationTs { get; set; }
        public string CreationUserId { get; set; }
        public Nullable<System.DateTime> LastChangeTs { get; set; }
        public string LastChangeUserId { get; set; }
        public byte StatusType { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
    	
    	[JsonIgnore]
        public virtual ICollection<Product> Product { get; set; }
    }
    
    #region Xenovex Technologies Customization for Validation - Metadata class declaration
    
    public partial class CategoryMetadata
    {
    
    }
    #endregion
    
}
