//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poc.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Newtonsoft.Json;
    
    
    [MetadataType(typeof(ProductMetadata))]
    public partial class Product
    {
        public int Id { get; set; }
        public string SessionId { get; set; }
        public System.DateTime CreationTs { get; set; }
        public string CreationUserId { get; set; }
        public Nullable<System.DateTime> LastChangeTs { get; set; }
        public string LastChangeUserId { get; set; }
        public byte StatusType { get; set; }
        public string ProductName { get; set; }
        public string QuantityPerUnit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<short> UnitsInStock { get; set; }
        public Nullable<short> UnitsOnOrder { get; set; }
        public Nullable<short> ReorderLevel { get; set; }
        public bool Discontinued { get; set; }
        public int UnitOfMeasure_Id { get; set; }
        public int Category_Id { get; set; }
    
    	
    	
        public virtual Category Category { get; set; }
    	
    	
        public virtual UnitofMeasure UnitofMeasure { get; set; }
    }
    
    #region Xenovex Technologies Customization for Validation - Metadata class declaration
    
    public partial class ProductMetadata
    {
    
    }
    #endregion
    
}
